//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbtest
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CMGPerson
    {
        public int CMGPersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ADAccount { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string HomePhone2 { get; set; }
        public string WorkPhone { get; set; }
        public byte[] RecordTimestamp { get; set; }
        public Nullable<System.DateTime> RecordLastModifiedDate { get; set; }
        public string RecordLastModifiedUser { get; set; }
        public System.DateTime RecordCreatedDate { get; set; }
        public string RecordCreatedUser { get; set; }
    }
}
