//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbtest
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CMGPortfolio
    {
        public int CMGPortfolioID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PortfolioAssetGroup { get; set; }
        public string PortfolioAssetCategory { get; set; }
        public Nullable<int> RefListID { get; set; }
        public bool ReviewedSinceCreated { get; set; }
        public byte[] RecordTimestamp { get; set; }
        public System.DateTime RecordLastModifiedDate { get; set; }
        public string RecordLastModifiedUser { get; set; }
        public string RecordLastModifiedIP { get; set; }
        public System.DateTime RecordCreatedDate { get; set; }
        public string RecordCreatedUser { get; set; }
        public string RecordCreatedIP { get; set; }
        public bool TestPortfolio { get; set; }
        public Nullable<int> BRSFundID { get; set; }
        public string BASE_CURRENCY { get; set; }
        public string COUNTRY { get; set; }
        public string CUSTODIAN { get; set; }
        public string CUSTODY_ACCT_NUM { get; set; }
        public Nullable<System.DateTime> INCEPT_DATE { get; set; }
        public string INVESTMENT_TYPE { get; set; }
        public string PORTFOLIO_TYPE { get; set; }
        public Nullable<System.DateTime> TERM_DATE { get; set; }
        public Nullable<int> CMGReconPortfolioID { get; set; }
        public Nullable<int> CMGRecordStatusID { get; set; }
        public bool ReconcileToIA { get; set; }
        public Nullable<System.DateTime> PerformanceInceptionDate { get; set; }
    }
}
